safe: false
source: .
destination: ./_site
plugins_dir: ./_plugin
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', '.asset-cache']

plugins:
  - jekyll-assets
  - jekyll-last-modified-at

title: "Alex Afanasyev, Ph.D."
description: 
author: Alex Afanasyev

baseurl: ""
url: ""

google:
  - analytics: UA-2395047-1

assets:
  compress:
    css: false
    js: true

  digest: false
  cache: .sass-cache
  features:
    automatic_img_size: false

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

scholar:
  style: _assets/bib/ieee.csl
  locale: en

  sort_by: year
  order: descending

  source: _assets/bib
  repository: assets/papers
  bibliography_template: bib-item

  bibtex_filters:
    - latex
    - markdown
